.DEFAULT_GOAL := help
SHELL := /bin/bash
COMPOSE := docker compose
PY ?= python3
SRC := src

.PHONY: help
help: ## Show this help
	@grep -hE '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) | sort | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}'

# --- local stack ------------------------------------------------------------

.PHONY: up
up: ## Start postgres, redis, mailhog, api, worker
	$(COMPOSE) up -d --wait postgres redis mailhog
	@echo "postgres  localhost:5433  (workbench_admin / workbench_admin)"
	@echo "mailhog   http://localhost:8025"
	@echo "next:     make migrate && make dev"

.PHONY: dev
dev: ## Run the API locally with reload (faster than the container)
	cd $(SRC) && uvicorn workbench.main:app --reload --port 8000

.PHONY: worker
worker: ## Run a Celery worker locally
	cd $(SRC) && celery -A workbench.workers.celery_app worker -l info -Q default,email,billing

.PHONY: down
down: ## Stop everything, keep volumes
	$(COMPOSE) down

.PHONY: nuke
nuke: ## Stop everything and delete the data
	$(COMPOSE) down -v

.PHONY: logs
logs: ## Tail logs
	$(COMPOSE) logs -f --tail=100

.PHONY: psql
psql: ## psql as the application role (RLS applies — this is what the app sees)
	$(COMPOSE) exec postgres psql -U workbench -d workbench

.PHONY: psql-admin
psql-admin: ## psql as the owner (RLS does not apply — use to inspect, not to debug)
	$(COMPOSE) exec postgres psql -U workbench_admin -d workbench

# --- migrations -------------------------------------------------------------

.PHONY: migrate
migrate: ## Apply migrations
	cd $(SRC) && alembic -c ../alembic.ini upgrade head

.PHONY: migrate-down
migrate-down: ## Roll back one migration
	cd $(SRC) && alembic -c ../alembic.ini downgrade -1

.PHONY: revision
revision: ## New autogenerated migration: make revision m="add widgets"
	@test -n "$(m)" || (echo 'usage: make revision m="description"'; exit 1)
	cd $(SRC) && alembic -c ../alembic.ini revision --autogenerate -m "$(m)"

.PHONY: migrate-test-db
migrate-test-db: ## Apply migrations to the test database
	cd $(SRC) && DATABASE_ADMIN_DSN=postgresql+asyncpg://workbench_admin:workbench_admin@localhost:5433/workbench_test \
		alembic -c ../alembic.ini upgrade head

# --- checks -----------------------------------------------------------------

.PHONY: check-rls
check-rls: ## Fail if any tenant table could leak (CI runs this)
	$(PY) scripts/check_rls.py

.PHONY: check-rls-test
check-rls-test: ## Same, against the test database
	$(PY) scripts/check_rls.py --dsn postgresql://workbench_admin:workbench_admin@localhost:5433/workbench_test

.PHONY: seed
seed: ## Development fixtures: two orgs, four users, one near quota, one staff
	$(PY) scripts/seed.py

# --- tests ------------------------------------------------------------------

.PHONY: install
install: ## Install dev dependencies
	$(PY) -m pip install -e ".[dev]"

.PHONY: test
test: ## Unit tests — no database needed
	$(PY) -m pytest tests -q -m unit

.PHONY: test-db
test-db: migrate-test-db ## The isolation suite. Needs the database running.
	$(PY) -m pytest tests -q -m database

.PHONY: test-all
test-all: test test-db check-rls ## Everything

.PHONY: test-cov
test-cov: ## Coverage report
	$(PY) -m pytest tests -q -m "unit or database" --cov=workbench --cov-report=term-missing

.PHONY: lint
lint: ## ruff + black check
	ruff check $(SRC) tests scripts
	black --check $(SRC) tests scripts

.PHONY: fmt
fmt: ## Auto-format
	ruff check --fix $(SRC) tests scripts
	black $(SRC) tests scripts

.PHONY: type
type: ## mypy
	mypy $(SRC)/workbench

# --- billing ----------------------------------------------------------------

.PHONY: stripe-listen
stripe-listen: ## Forward Stripe webhooks to the local API
	@test -n "$$STRIPE_SECRET_KEY" || (echo "set STRIPE_SECRET_KEY in your shell first"; exit 1)
	stripe listen --forward-to localhost:8000/webhooks/stripe

.PHONY: stripe-trigger
stripe-trigger: ## Fire a test webhook
	stripe trigger checkout.session.completed

.PHONY: plans
plans: ## Print the plan catalogue and the permission matrix
	@$(PY) -c "import sys; sys.path.insert(0,'$(SRC)'); from workbench.billing.entitlements import all_plans; import json; print(json.dumps(all_plans(), indent=2))"
	@echo
	@$(PY) -c "import sys; sys.path.insert(0,'$(SRC)'); from workbench.core.permissions import describe_matrix; [print(f\"  {r['permission']:22} {', '.join(r['roles'])}\") for r in describe_matrix()]"

# --- packaging ---------------------------------------------------------------

.PHONY: package
package: ## Build dist/workbench-<version>.tar.gz
	@bash scripts/package.sh

.PHONY: smoke
smoke: ## End-to-end smoke test against a running API (scripts/smoke.sh)
	@bash scripts/smoke.sh "$${API_BASE_URL:-http://localhost:8000}"

.PHONY: clean
clean: ## Remove caches, build output and the virtualenv
	rm -rf dist build .pytest_cache .ruff_cache .mypy_cache .coverage htmlcov
	find . -type d -name __pycache__ -prune -exec rm -rf {} +
	@echo "clean"
